name: Hourly AQI Data Collection

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour
  workflow_dispatch:      # Allow manual triggers for testing

jobs:
  collect-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r feature_pipeline/requirements.txt
        
    - name: Create .env file
      run: |
        echo "AQICN_API_TOKEN=${{ secrets.AQICN_API_TOKEN }}" >> .env
        echo "HOPSWORKS_API_KEY=${{ secrets.HOPSWORKS_API_KEY }}" >> .env
      
    - name: Run feature pipeline
      run: python feature_pipeline/feature_pipeline.py
      
    - name: Handle potential failures
      if: failure()
      run: |
        echo "Data collection failed at $(date)" >> $GITHUB_STEP_SUMMARY
        echo "Please check the workflow logs for more details."